### ISSUE TITLE
Data Sources

### ISSUE THREAD

**Issue by delphiactual** [BrianWhiting/DestinyCollections#1]
DIM already has a repo of extra data information incase you would like this information instead of having to figure it out on your own.
PRs welcome, and we can shape or adjust data as needed.

https://github.com/DestinyItemManager/d2-additional-info
https://github.com/DestinyItemManager/d2ai-module

**Comment by BrianWhiting** [comment]
Thanks for the heads up! I'll keep this in mind as I develop this project.
